### ISSUE TITLE
image_optim.yml

### ISSUE THREAD

**Issue by ahmgeek** [toy/image_optim#108]
I've added the config file in <code>config/</code> inside my rails app ass ```.image_optim.yml```
and also tried ```image_optim.yml``` without any hope to work !
I don't have the pleasure to put it in ```.config/``` in the deployment as its heroku.
is there anything wrong I do ?

**Comment by toy** [comment]
You need to either put the `.image_optim.yml` in the application root directory or put it in `config/image_optim.yml` and add `config.assets.image_optim.config_path = 'config/image_optim.yml'` to rails config.

**Comment by ahmgeek** [comment]
I've did that, thanks a bunch.
however, rails raised some errors due  to these configs

```
jpeg:
  jhead:
  jpegoptim:
    strip: all
    max_quality: 75
  jpegtran:
    copy_chunks: false
    progressive: true
    jpegrescan: false
  jpegrecompress:
    quality: 2
png:
  pngcrush:
    chunks: alla
    fix: false
    brute: false
    blacken: true
  optipng:
    level: 4
    interlace: false
    strip: true
  pngquant:
    quality: 100..100
    speed: 3
  advpng:
    level: 4
gif:
  gifsicle:
    interlace: false
    level: 3
    careful: false
  gifsicle:
    interlace: true
    level: 3
    careful: false
```

any configuration file around I can cheat from ?
